//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATABASE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DATABASE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20230418_86JDjvN9rKen {
            get {
                object obj = ResourceManager.GetObject("20230418_86JDjvN9rKen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2b54c9bc347baca220dcb65b174a5806 {
            get {
                object obj = ResourceManager.GetObject("2b54c9bc347baca220dcb65b174a5806", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _61TZu_kjbKL__AC_SL1500_ {
            get {
                object obj = ResourceManager.GetObject("61TZu+kjbKL._AC_SL1500_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7046204 {
            get {
                object obj = ResourceManager.GetObject("7046204", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84c176b2960090acd04cdda9db50d805_jpg_720x720q80 {
            get {
                object obj = ResourceManager.GetObject("84c176b2960090acd04cdda9db50d805.jpg_720x720q80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _962c0060e40794e097c90bc659163dc7 {
            get {
                object obj = ResourceManager.GetObject("962c0060e40794e097c90bc659163dc7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _98ffb957671f891b46c7876e06354c15 {
            get {
                object obj = ResourceManager.GetObject("98ffb957671f891b46c7876e06354c15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _98ffb957671f891b46c7876e06354c151 {
            get {
                object obj = ResourceManager.GetObject("98ffb957671f891b46c7876e06354c151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_gradient_pink_blue_liquid_wave_background_free_vector {
            get {
                object obj = ResourceManager.GetObject("abstract-gradient-pink-blue-liquid-wave-background-free-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_gradient_pink_blue_liquid_wave_background_free_vector1 {
            get {
                object obj = ResourceManager.GetObject("abstract-gradient-pink-blue-liquid-wave-background-free-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_gradient_pink_blue_liquid_wave_background_free_vector2 {
            get {
                object obj = ResourceManager.GetObject("abstract-gradient-pink-blue-liquid-wave-background-free-vector2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ao_so_mi_mau_hong_coc_tay_5 {
            get {
                object obj = ResourceManager.GetObject("ao-so-mi-mau-hong-coc-tay-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASM18_20 {
            get {
                object obj = ResourceManager.GetObject("ASM18-20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bia_tap_chi_2_mat_chup_anh_thoi_trang_1 {
            get {
                object obj = ResourceManager.GetObject("bia-tap-chi-2-mat-chup-anh-thoi-trang-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap channels4_profile {
            get {
                object obj = ResourceManager.GetObject("channels4_profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chup_anh_quan_ao {
            get {
                object obj = ResourceManager.GetObject("chup-anh-quan-ao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chup_anh_quan_ao2 {
            get {
                object obj = ResourceManager.GetObject("chup-anh-quan-ao2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d7e573f1ea5186d362262a9326414217 {
            get {
                object obj = ResourceManager.GetObject("d7e573f1ea5186d362262a9326414217", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e074cb06e3bc9b3c789b7df92ad5d454 {
            get {
                object obj = ResourceManager.GetObject("e074cb06e3bc9b3c789b7df92ad5d454", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e074cb06e3bc9b3c789b7df92ad5d4541 {
            get {
                object obj = ResourceManager.GetObject("e074cb06e3bc9b3c789b7df92ad5d4541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ee33ba62_8ac3_46af_a619_8601aa0e14a1 {
            get {
                object obj = ResourceManager.GetObject("ee33ba62-8ac3-46af-a619-8601aa0e14a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ee33ba62_8ac3_46af_a619_8601aa0e14a1__1_ {
            get {
                object obj = ResourceManager.GetObject("ee33ba62-8ac3-46af-a619-8601aa0e14a1 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap H9f3a7e4b301a4409b9b80ab266c6e4dcY {
            get {
                object obj = ResourceManager.GetObject("H9f3a7e4b301a4409b9b80ab266c6e4dcY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KK170_26 {
            get {
                object obj = ResourceManager.GetObject("KK170-26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lan_ngịc {
            get {
                object obj = ResourceManager.GetObject("lan ngịc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mau_background_hong_nhat_trang_012201210 {
            get {
                object obj = ResourceManager.GetObject("mau-background-hong-nhat-trang_012201210", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mau_background_hong_nhat_trang_0122012101 {
            get {
                object obj = ResourceManager.GetObject("mau-background-hong-nhat-trang_0122012101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cartoon_line_chart_icon_download_image_1251432 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cartoon-line-chart-icon-download-image_1251432", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_clothing_icon_image_1144362 {
            get {
                object obj = ResourceManager.GetObject("pngtree-clothing-icon-image_1144362", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_customer_care_icon_man_symbol_on_hand_sign_png_image_1873961 {
            get {
                object obj = ResourceManager.GetObject("pngtree-customer-care-icon-man-symbol-on-hand-sign-png-image_1873961", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_returning_customer_icon_vectorexisting_customer_icon_user_support_practice_vector_png_image_12693166 {
            get {
                object obj = ResourceManager.GetObject("pngtree-returning-customer-icon-vectorexisting-customer-icon-user-support-practic" +
                        "e-vector-png-image_12693166", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quan_Short_Jean_Nu_tron_tua_lai_mau_hong_tt92_1 {
            get {
                object obj = ResourceManager.GetObject("Quan-Short-Jean-Nu-tron-tua-lai-mau-hong-tt92-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sg_11134201_22100_prnxorlu64iv98 {
            get {
                object obj = ResourceManager.GetObject("sg-11134201-22100-prnxorlu64iv98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sg_11134201_22100_prnxorlu64iv981 {
            get {
                object obj = ResourceManager.GetObject("sg-11134201-22100-prnxorlu64iv981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sg_11134202_7rcdc_lts16k1029zt10 {
            get {
                object obj = ResourceManager.GetObject("sg-11134202-7rcdc-lts16k1029zt10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sn_diep_bao_ngoc_1_1 {
            get {
                object obj = ResourceManager.GetObject("sn-diep-bao-ngoc-1-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thiet_ke_website_thoi_trang_chuyen_nghiep_1 {
            get {
                object obj = ResourceManager.GetObject("thiet-ke-website-thoi-trang-chuyen-nghiep-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vn_11134201_7qukw_lh8m2z50z9wz2c {
            get {
                object obj = ResourceManager.GetObject("vn-11134201-7qukw-lh8m2z50z9wz2c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
